version: '3'
services:
  arclight:
    environment:
      - SWIFT_USERNAME=xxx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    volumes:
      - /root/demo-blacklight:/app
    networks:
      - arclighttest
networks:
  arclighttest:
