heritage:
  name: 'Heritage'
  description: ''
  contact_html: |
    <div class="al-repository-contact-phone">123-456-7890</div>
    <div class="al-repository-contact-info"><a href="mailto:blapierre@crkn.ca">blapierre@crkn.ca</a></div>
  location_html: |
    <div class="al-repository-street-address-building">Libraries and Archives Canada</div>
    <div class="al-repository-street-address-address1">395 Wellington St</div>
    <div class="al-repository-street-address-city_state_zip_country">Ottawa, ON K1A 0N4, Canada</div>
  thumbnail_url: 'https://www.crkn-rcdr.ca/sites/default/themes/crkn/images/logo/crkn-logo.svg'
  url: 'https://www.crkn-rcdr.ca/en'